appId: app.rcf.visioncast.freeshow
productName: RCF VisionCast

directories:
  output: dist
  buildResources: build/public

files:
  - build/electron/**
  - build/types/**
  - public/**
  - "!node_modules/@napi-rs"
  - "!node_modules/@napi-rs/canvas-android-*"
  - "!node_modules/@napi-rs/canvas-linux-*"
  - "!node_modules/@napi-rs/canvas-darwin-*"

extraResources:
  - from: node_modules/slideshow/
    to: slideshow
    filter:
      - connector-*

# Windows configuration
win:
  target: NSIS
  icon: build/public/icon.png

nsis:
  oneClick: false
  perMachine: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
